### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Josefinacm** [Beyondactivismo/Beyondactivismo#10]

**Comment by denefi** [comment]
Hey guys, on the readme we refere to CC 4.0 licence but the license file is a MIT license. Maybe we should use the same license at all instances as to avois confusion. I Guess CC 4.0 is more apropiated because our content is content driven and not that much about coiding.

**Comment by dannyrayman** [comment]
I have had the same doubt @denefi, and I also think that the best is the CC.4.O. but they recommend me to put the license for the code in MIT and for non code content the CC.4.0. And If you try to put the license of CC.4.0 in the https://github.com/Beyondactivismo/Beyondactivismo/community part of License it doesn't match then. I think we can let it that way for the moment.

**Comment by denefi** [comment]
MIT License was choosen for code, CC BY 4.0 was chosen for content.
