### ISSUE TITLE
GUIDELINES

### ISSUE THREAD

**Issue by triaslucia** [Beyondactivismo/Beyondactivismo#19]
Comment or Requests on GUIDELINES

**Comment by dannyrayman** [comment]
Great @triaslucia ! 

About your comments:
1) It is a very good Idea and I agree. If we have from the very beginning the answer of the interviewee about his need to stay anonymous, only after that the collaborator will know that he can use a specific protocol and the related toolkit. 

We talked about that with Hadi form the Syrian Archive and he recommend us to have two different protocols depending if the source (in our case activist) want to stay anonymous or not. 

2) Yes of course can we change it. We just follow a basic interview structure, so you can fix it 👍  

You are free to edit, we all can see when you change something. If you go to the file you can see the history and the changes that somebody does.

**Comment by denefi** [comment]
@triaslucia  [GUIDELINES](https://github.com/Beyondactivismo/Beyondactivismo/edit/master/GUIDELINES/toolkit/3_Questions%20guideline.md) on line 32, seperate users into written Interview, Audio, and Video and provide specific Resources to each.
