### ISSUE TITLE
Logo BA Image

### ISSUE THREAD

**Issue by Beyondactivismo** [Beyondactivismo/Beyondactivismo#2]
![logo final ba](https://user-images.githubusercontent.com/37877591/38767723-29cac5ee-3fe7-11e8-99c2-456c9d5ef279.png)

**Comment by dannyrayman** [comment]
![logo redes copia](https://user-images.githubusercontent.com/32823481/38769818-653a032a-4009-11e8-8ab4-870897539466.jpg)
