### ISSUE TITLE
Pitching BA

### ISSUE THREAD

**Issue by denefi** [Beyondactivismo/Beyondactivismo#20]
We need a short Pitch in english for ourselfs and future collaborators that approach interviewees. 
 I think it should

- not be longer than 2min (less even better)
- explain who we are, what problem we try to solve an how we solve it
- we should make a video

This issue is connected to #15 #18

**Comment by triaslucia** [comment]
If we prepare the Info I can do some basic 'slides' animation

**Comment by dannyrayman** [comment]
Great I think in the same way. That would be great Lu, I asked to my cuisine if he can help us with the video. Maybe he join us.

**Comment by Josefinacm** [comment]
Hola, les escribo en español porque es más rápido.
Joaquin el primo de Danny nos va a ayudar haciendo un video, les dejo sus comentarios para que empecemos a trabajar en esto lo antes posible.

**Comentarios Joaquin**
A continuación las dudas y consejos con respecto a lo que necesitan:

1) ¿El video incluye material grabado de ustedes (acción real) o es solo de animaciones gráficas?
2) ¿Tienen alguna especie de guión con lo que quieren que trate, más o menos a grandes rasgos (yo lo puedo resumir). La idea sería tener este guión de una página con las ideas principales lo más sintéticas y visuales posibles para ser traducidas mediante imagenes y palabras a modo de animación gráfica. Aquí un ejemplo sencillo que hice hace algún tiempo: https://www.youtube.com/watch?v=4vl_41rhmxM

Para lograr esto:
A) Se trabaja un texto (que resultará en la voz en off, se cronometra el texto para saber el tiempo estimado del video). Tiene que ser lo más sintetico y al callo posible.
B) Junto a un diseñador gráfico idealmente, este desarrolla cada plantilla (en adobe illustrator por capas) con la información del texto, puntualizando los conceptos principales y otorgandole una forma lúdica y amena mediante iconos, palabras, etc.
C) Se busca una música adoc al tono del video libre de derechos.
D) Se animan los videos en Adobe after effect. (La animación dependiendo de la complejidad también toma su tiempo, aún siendo algo simple).

Mientras menos información escrita tenga el video más atractivo. Ideal que tenga imágenes sencillas y fáciles de animar. La voz en off resultante tiene que ser también lo más sintética y clara en las ideas que expone.

3) ¿Tienen alguna estetica desarrollada? paleta de colores, tipográfia, etc?

**Comment by joaquinrl** [comment]
Hello, Joaquin here. I shall be attentive to this issue. 
Is there any way to receive an email notification when you are updating the progress in this issue?

**Comment by dannyrayman** [comment]
Great @joaquinrl !

I send you and invitation to our project to collaborate when you acept I can add you to this Issue and then Github will notify you.

A big hug!

**Comment by joaquinrl** [comment]
I received a email notification automatically when you answered me,
we are talking

**Comment by Beyondactivismo** [comment]
Hi @ceharji thanks for help us with your voice, here will be talking about the video and you can meet everyone that is helping with this Issue.

**Comment by ceharji** [comment]
Hello :) Carmen here!!

**Comment by triaslucia** [comment]
PITCH 

Introduccion: 
Alguna vez te has puesto a pensar que es lo que motiva a personas de diferentes partes del mundo a luchar por una causa relacionada con DH ?

Que:
Beyond Activismo busca documentar las historias y experiencias de activistas alrededor del mundo. Con el fin de generar una red de ayuda mutua, donde a la vez puedan motivar a personas a participar en causas relacionadas a los derechos humanos.

Como:  
a través del sitio web www.beyondactivismo.org, basado en los principios de Openness, Decentralization and Digital Inclusion. El contenido se compartirá en diferentes idiomas, para que este no sea una barrera entre las diferentes partes del mundo. 

Porque:

Ya que creemos que visibilizando estas historias podemos realizar un cambio

Te invitamos a colaborar con nosotros este 10 y 11 de mayo en Mozilla Global Sprint

**Comment by Josefinacm** [comment]
**Introduction**
Have you ever wonder what motivates people from every part of the world to fight for a cause related to human rights?

**What**
Beyond Activismo wants to document the histories and experiences of activists around the world with the objective to generate a network between them, where also people can feel motivated it to participate in causes related with human rights.

**How**
Through the website www.beyondactivismo.org, based on principles of Openness, Decentralization and Digital Inclusion, the content will be shared in different languages so that this is not a barrier between different parts of the world.

**Why**
Because we believe that making visible this histories we can make a change.
We invite you to collaborate with us this 10 and 11 May in Mozilla Global Sprint.

**Comment by joaquinrl** [comment]
Hello, sorry if it's too late, here is a similar version but I change a few things giving a diferent point of view. Read them and if you like, we could try to work on this. You can reformulate any sentences. 
But if there is no time, doesn't matter. We can continue with previous text.
__________________________

_(Sería bonito iniciar el video (o finalizarlo ) con un saludo o despedida en diferentes idiomas, puede ser una plantilla en el que esté escrito un saludo o una frase en inglés, francés, español, portugués, sirio, japonés, etc. 
Aquí una referencia - https://www.youtube.com/watch?v=4YAYGi8rQag (7:44 en adelante, son como 10 segundos. La idea sería hacerlo pero más en la lógica de motion graphics, Quizá la frase ¿Que te motivaría a luchar por los DH?)_

¿Que te motivaría a luchar por los DH?
Muchas personas a lo largo de la historia han actuado para proteger y defender los DH.
¿Es esto suficiente?
Beyond Activismo busca documentar las historias y experiencias 
de los activistas 
alrededor del mundo,
con el fin de generar una red de ayuda mutua
y motivar la participación en causas relacionadas a los derechos humanos.

Tendrás todo el contenido disponible en www.beyondactivismo.org,
en diferentes idiomas,
para que este no sea una barrera 
entre las diferentes partes del mundo.

Nuestro sitio está basado en los principios de
Openness, 
Decentralization 
and Digital Inclusion. 

SI quieres participar y saber más acerca de estos principios, escríbenos.

Creemos que visibilizando estas historias 
podemos realizar un cambio
Te invitamos a colaborar con nosotros este 
10 y 11 de mayo 
en Mozilla Global Sprint
