### ISSUE TITLE
Upload Form for Content Colaborators

### ISSUE THREAD

**Issue by denefi** [Beyondactivismo/Beyondactivismo#21]
Define:

How is the upload procedure for our collaborators. It needs to be fast, secure and provide ous with all the necesary information.

Please read this [File](https://github.com/Beyondactivismo/Beyondactivismo/blob/master/GUIDELINES/toolkit/4_Uploading.md).

**Comment by dannyrayman** [comment]
The solution that we arrive we have to implement it in the  #23 submission (page)

**Comment by denefi** [comment]
Secure Drop? https://docs.securedrop.org/

**Comment by denefi** [comment]
@dannyrayman podrias escribirles a los que hacen nuestro hosting si ellos tienen posibilidad de implementar securedrop

**Comment by triaslucia** [comment]
IF I try to read the file it says 'not found'

**Comment by Beyondactivismo** [comment]
@triaslucia the link was not right now can you click on file and visit the Guide.
