### ISSUE TITLE
Contributing.md for Mozsprint

### ISSUE THREAD

**Issue by dannyrayman** [Beyondactivismo/Beyondactivismo#22]
- Developers Contributors: 
1. Wordpresss Theme 
2. Ideas or Solutions to work open with Wordpress

- Feedback Contributors:
1. Suggestions, comments and critics to our project.
2. Suggest a Interview to an Activist

- Content Contributors: 
1. Do an Interview to an Activist
2. Translate
3. Artist contributions

**Comment by Josefinacm** [comment]
**HI EVERYBODY!** 😃 😃 🎉 🎉 

**ARE YOU INTERESTED IN COLLABORATE WITH US IN MOZILLA OPEN SPRINT?**

**What do we need?**

 _**1) Developers Contributors:**_
- **Wordpress Theme:**
 People who know how to work with wordpress.

- **Ideas or Solutions to work open with Wordpress:** 
People that could give to us ideas or solutions to work open with Wordpress.

_**2) Feedback Contributors:**_
- **Suggestions, comments and constructive criticims to our project:** 
Your opinion is fundamental for us, please give it to us!

- **Suggest an Interview for an Activist:** 
Do you know some activist to make them an interview? Please let us know! 😃 

_**3) Content Contributors:**_

- **Do an Interview to an Activist:**
If you know an activist and would like to make an interview with our [Contributing Guideline for Interviewers.](https://user-images.githubusercontent.com/32823481/38769888-7f244cea-400a-11e8-80a7-293dc415c086.png)

- **Translate:** 
Do you want to translate our content in other languages? Please help us! In that way the language will not be an obstacle anymore 😃 💪 💪  

- **Artist contributions:** If you are a:

1) Filmmaker: You can film our interviews and documenting the interviewees activists.

2) Photographer: Through the photographies you can documenting the work of activists.

3) Illustrator: You can make the visual of BA more attractive. 

4) Game designer: You can make animations for BA, improve storytelling

5) Multimedia and animator:

6) Musician: You can musicalize the documentation of the interviews of Beyond Activismo:
