### ISSUE TITLE
Stickers Beyond Activismo

### ISSUE THREAD

**Issue by dannyrayman** [Beyondactivismo/Beyondactivismo#32]
Buy Stickers with the logo and website of Beyond Activismo.

@triaslucia did you received an answer from your friend?

**Comment by triaslucia** [comment]
no! if you wanna order it by internet we can do it. I normaly prefer to see a sample on this kind of stuff. but I´ll guess it´s fine. 

Anyway you need to take care of the 'safe zone'....shall I do the document and send it?

**Comment by dannyrayman** [comment]
Yes great @triaslucia that would be perfect. The page if you want to know is www.vistaprint.de
