### ISSUE TITLE
Who is Beyond Activismo?

### ISSUE THREAD

**Issue by cameralibre** [Beyondactivismo/Beyondactivismo#54]
The README is a nice introduction to the project, but I don't get any sense of who the people behind the project are, and why they are motivated to work on it... 
I think that your video will help to address this, which is great. 

But I wanted to share _one more_ easy idea which you could think about implementing in addition: an introductions thread.

The other project I'm mentoring is _We Are All Connected_, and they have added an [introductions issue](https://github.com/EducationalVideoCenter/WAC/issues/5) for project participants and new contributors to say hi. If you wanted to set up a similar issue, I think the best way to do it would be to call the issue something like **Introductions: Welcome to Beyond Activismo!** with a short introduction, like the WAC issue:
`If you are interested in this project, even if you're not sure how to contribute, please say "Hi" and tell us a bit about yourself, and why you're interested in the topic of activism. `
Then each of you can comment on the issue:
`Hi, I'm Josefina... this is my background... this is why I'm interested in working on Beyond Activismo... this is how I contribute... `

**Comment by denefi** [comment]
Hey Sam, 
We were trying to do something like that here: #46 I really like the Idea of posting ourself a little presentation.

**Comment by denefi** [comment]
@cameralibre This is the [Pad](
https://public.etherpad-mozilla.org/p/Pitch-BeyonActivismo) were we are working on the topics of `what? how? and why?`:  Yo can have a look. I guess all of us have different motivations to participate in the project wich ist actually something we shouldn't hide, as it gives a more personal touch to people who are learning about the project for the first time. We are also working on a projectwide `why?` at the same time to include it in the video and in future presentations of the project, though.

**Comment by cameralibre** [comment]
ah, great to see that you're already doing this! sorry, I had missed #46. 
> We could also do it as a comment instead of putting it in the issues desvription, maybe we'll help to break the ice by doing so.

yes, @denefi I think this is a great idea to help welcome participants in, because it does not create a barrier between the 'team members' (who are in the description) and the 'other contributors' who are in the thread. If you each individually add a comment in the thread, it is more of a conversation, and it creates a rhythm and a space for others to follow your lead and introduce themselves too.

**Comment by denefi** [comment]
Issue solved by creating #46
