### ISSUE TITLE
Who is Behind Beyond Activismo?

### ISSUE THREAD

**Issue by dannyrayman** [Beyondactivismo/Beyondactivismo#57]
![captura de pantalla 2018-04-14 a las 5 36 52 p m](https://user-images.githubusercontent.com/32823481/38769888-7f244cea-400a-11e8-80a7-293dc415c086.png) 

The main idea from Beyond Activismo is that everyone makes Beyond Activismo, if you contribute or not it doesn't matter. Your visit, your comment, your suggestion help us grow as a project and as a team. 

That is why we kindly invite you whether you are interested in this project or not, even if you are not sure how to contribute, to say "Hi" and tell us a bit about yourself.

We will start, here's a little about the Beyond Activismo team:

@Josefinacm : 

@denefi :

@triaslucia : 

@dannyrayman :
 
We hope you feel welcomed to this project!! 😃

**Comment by denefi** [comment]
Issue moved to #46
